### ISSUE TITLE
Naming conflict with existing open source project

### ISSUE THREAD

**Issue by steverfrancis** [DigitalPatterns/talospi#2]
Note that there is opportunity for confusion with 
https://github.com/talos-systems/talos

which also publishes k8s on pi:
https://www.talos.dev/docs/v0.8/single-board-computers/rpi_4/

which is the first or second result for googling "talos pi"

It would be appreciated if this project is renamed to avoid confusion and later legal complications.

**Comment by pixie79** [comment]
Thank you for the notice, but the name talos aligns with our product and these are instructions for installing a dev environment based on a pi. 
You will note kubernetes is not restrictive and anyone can publish instructions for build and development.

Likewise the name talos is also not protected and used for many products as such a claim for ownership would be very hard.

Whilst I can see your confusion I think a competent person can see the differences.

Regards
